import test from 'node:test';
import assert from 'node:assert/strict';
import net from 'node:net';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';
import { performance } from 'node:perf_hooks';
import { Client } from '@modelcontextprotocol/client';
import { StdioClientTransport } from '@modelcontextprotocol/client/stdio';
import { resetCustomers } from '../../src/customer-store.mjs';
import { postJson, requestJson } from '../../src/http-json.mjs';
import { verifyRemoteAccessToken } from '../../src/oauth-client.mjs';
const here=path.dirname(fileURLToPath(import.meta.url));const root=path.resolve(here,'../..');const audience='urn:gate:mcp:customer-service';const demoMode=process.argv.includes('--demo');
async function freePort(){return new Promise((resolve,reject)=>{const s=net.createServer();s.once('error',reject);s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(e=>e?reject(e):resolve(p))})})}
function startService(relative,env={}){const child=spawn(process.execPath,[path.join(root,relative)],{cwd:root,env:{...process.env,...env},stdio:['ignore','pipe','pipe']});child.stderr.on('data',d=>process.stderr.write(`[${relative}] ${d}`));return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(`${relative} did not become ready`)),7000);child.stdout.on('data',d=>{for(const line of d.toString().split(/\r?\n/)){if(!line.trim())continue;try{const msg=JSON.parse(line);if(msg.ready&&msg.url){clearTimeout(timer);resolve({child,url:msg.url,...msg});return}}catch{}}});child.on('exit',code=>{clearTimeout(timer);reject(new Error(`${relative} exited ${code}`))})})}
async function stop(s){if(!s?.child||s.child.killed)return;s.child.kill('SIGTERM');await new Promise(r=>setTimeout(r,30))}
function parseTool(result){const t=result.content?.find(x=>x.type==='text')?.text;if(!t)return null;try{return JSON.parse(t)}catch{return{rawText:t}}}
function print(label,value){if(!demoMode)return;console.log(`\n=== ${label} ===`);console.log(JSON.stringify(value,null,2))}
async function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
async function waitRevision(edgeUrl,min,{timeout=3000}={}){const end=Date.now()+timeout;while(Date.now()<end){const s=await requestJson(`${edgeUrl}/v1/replica/status`);if(s.revision>=min&&s.fresh)return s;await sleep(25)}throw new Error(`edge ${edgeUrl} did not reach revision ${min}`)}
function pct(values,p){const a=[...values].sort((x,y)=>x-y);return a[Math.min(a.length-1,Math.floor((a.length-1)*p))]}
async function benchmark(edgeUrl,n=100){const times=[];for(let i=0;i<n;i++){const t=performance.now();const r=await postJson(`${edgeUrl}/v1/authority/verify`,{principal:'user:jerome',actor:'agent:C@company-c',consistency:'bounded',maxStalenessMs:200});assert.equal(r.decision,'ALLOW');times.push(performance.now()-t)}return{samples:n,p50Ms:+pct(times,.50).toFixed(3),p95Ms:+pct(times,.95).toFixed(3),p99Ms:+pct(times,.99).toFixed(3),maxMs:+Math.max(...times).toFixed(3)}}
function mcpClient({token,pdpUrl,issuerUrl,customerPath,name}){const client=new Client({name,version:'0.8.0'});const transport=new StdioClientTransport({command:process.execPath,args:[path.join(root,'mcp','server.mjs')],env:{...process.env,GATE_DEMO_ACCESS_TOKEN:token,AUTHZEN_URL:pdpUrl,OAUTH_ISSUER_URL:issuerUrl,GATE_AUDIENCE:audience,CUSTOMER_STORE_PATH:customerPath}});return{client,transport}}
async function runScenario(){
  const keys=['trust','oauth','control','principal','a','b','rogue','east','west','pdpEast','pdpWest'];const ports={};for(const k of keys)ports[k]=await freePort();const u=Object.fromEntries(Object.entries(ports).map(([k,v])=>[k,`http://127.0.0.1:${v}`]));const eventType='https://gate.example/events/authority-edge-state';
  const members={[u.principal]:{principal_patterns:['user:*'],events_supported:[eventType]},[u.a]:{principal_patterns:['agent:*@company-a'],events_supported:[eventType]},[u.b]:{principal_patterns:['agent:*@company-b'],events_supported:[eventType]},[u.rogue]:{principal_patterns:['agent:*@rogue'],events_supported:[eventType]}};
  const customerPath=path.join(root,'state','customers.json');resetCustomers(customerPath);let trust,control,principal,txA,txB,issuer,east,west,pdpEast,pdpWest,eastMcp,westMcp;
  try{
    trust=await startService('services/trust-anchor.mjs',{PORT:String(ports.trust),FEDERATION_MEMBERS_JSON:JSON.stringify(members)});
    control=await startService('services/gate-control-plane.mjs',{PORT:String(ports.control),TRUST_ANCHOR_URL:u.trust,LEASE_TTL_MS:'1000'});
    principal=await startService('services/authority-transmitter.mjs',{PORT:String(ports.principal),AUTHORITY_DOMAIN:'principal',GATE_CONTROL_PLANE_URL:u.control});
    txA=await startService('services/authority-transmitter.mjs',{PORT:String(ports.a),AUTHORITY_DOMAIN:'company-a',GATE_CONTROL_PLANE_URL:u.control});
    txB=await startService('services/authority-transmitter.mjs',{PORT:String(ports.b),AUTHORITY_DOMAIN:'company-b',GATE_CONTROL_PLANE_URL:u.control});
    issuer=await startService('services/oauth-issuer.mjs',{PORT:String(ports.oauth)});
    east=await startService('services/gate-edge.mjs',{PORT:String(ports.east),CONTROL_PLANE_URL:u.control,GATE_REGION:'east',REPLICA_POLL_MS:'25',DEFAULT_MAX_STALENESS_MS:'200'});
    west=await startService('services/gate-edge.mjs',{PORT:String(ports.west),CONTROL_PLANE_URL:u.control,GATE_REGION:'west',REPLICA_POLL_MS:'25',DEFAULT_MAX_STALENESS_MS:'200'});
    pdpEast=await startService('services/authzen-pdp.mjs',{PORT:String(ports.pdpEast),GATE_EDGE_URL:u.east,OAUTH_ISSUER_URL:u.oauth,GATE_AUDIENCE:audience,GATE_CONSISTENCY:'bounded',GATE_MAX_STALENESS_MS:'200'});
    pdpWest=await startService('services/authzen-pdp.mjs',{PORT:String(ports.pdpWest),GATE_EDGE_URL:u.west,OAUTH_ISSUER_URL:u.oauth,GATE_AUDIENCE:audience,GATE_CONSISTENCY:'bounded',GATE_MAX_STALENESS_MS:'200'});
    print('1. CONTROL PLANE + TWO REGIONAL EDGE REPLICAS ONLINE',{trustAnchor:trust.url,controlPlane:control.url,edgeEast:east.url,edgeWest:west.url,pdpEast:pdpEast.url,pdpWest:pdpWest.url});
    await postJson(`${principal.url}/demo/emit`,{edgeId:'edge-human-agent-a',status:'ACTIVE'});await postJson(`${principal.url}/demo/emit`,{edgeId:'edge-human-agent-b',status:'ACTIVE'});await postJson(`${txA.url}/demo/emit`,{edgeId:'edge-agent-a-agent-c',status:'ACTIVE'});await postJson(`${txB.url}/demo/emit`,{edgeId:'edge-agent-b-agent-c',status:'ACTIVE'});
    const eastReady=await waitRevision(east.url,4);const westReady=await waitRevision(west.url,4);print('2. SIGNED REPLICA LEASES ARE FRESH IN BOTH REGIONS',{east:eastReady,west:westReady,consistencyContract:{boundedMaxStalenessMs:200,strictMode:'synchronous control-plane confirmation; fail closed if unreachable'}});
    const tokenResponse=await postJson(`${issuer.url}/token`,{principal:'user:jerome',actor:'agent:C@company-c',audience,customerIds:['1234','2345','3456','4567','5678']});const token=tokenResponse.access_token;const tokenCheck=await verifyRemoteAccessToken({token,audience,allowedIssuer:issuer.url});assert.equal(tokenCheck.valid,true);
    eastMcp=mcpClient({token,pdpUrl:pdpEast.url,issuerUrl:issuer.url,customerPath,name:'gate-v0.8-east'});westMcp=mcpClient({token,pdpUrl:pdpWest.url,issuerUrl:issuer.url,customerPath,name:'gate-v0.8-west'});await eastMcp.client.connect(eastMcp.transport);await westMcp.client.connect(westMcp.transport);
    const first=parseTool(await eastMcp.client.callTool({name:'delete_customer_data',arguments:{customerId:'1234'}}));assert.equal(first.executed,true);print('3. LOCAL EDGE AUTHORITY CHECK PERMITS REAL MCP ACTION',first);
    const bench=await benchmark(east.url,100);print('4. LOCAL EDGE VERIFY LATENCY (LOOPBACK BENCHMARK, NOT INTERNET SLA)',bench);
    await postJson(`${principal.url}/demo/emit`,{edgeId:'edge-human-agent-a',status:'REVOKED',reason:'principal_revoked_agent_a'});await waitRevision(east.url,5);await waitRevision(west.url,5);const second=parseTool(await westMcp.client.callTool({name:'delete_customer_data',arguments:{customerId:'2345'}}));assert.equal(second.executed,true);assert.equal(second.authzen.context.gate.validPathCount,1);print('5. REVOCATION PROPAGATES; ALTERNATE PATH STILL AUTHORIZES',second);
    await postJson(`${west.url}/demo/network/partition`,{});await sleep(230);const westStale=await requestJson(`${west.url}/v1/replica/status`);assert.equal(westStale.fresh,false);print('6. WEST REGION PARTITIONED; FRESHNESS LEASE EXPIRES FOR BOUNDED POLICY',{west:westStale,note:'GATE refuses stale ALLOW once requested freshness bound is exceeded'});
    await postJson(`${principal.url}/demo/emit`,{edgeId:'edge-human-agent-b',status:'REVOKED',reason:'principal_revoked_agent_b'});const eastAfter=await waitRevision(east.url,6);print('7. FINAL REVOCATION REACHES HEALTHY EAST REGION',eastAfter);
    const eastBlockedRaw=await eastMcp.client.callTool({name:'delete_customer_data',arguments:{customerId:'3456'}});const eastBlocked=parseTool(eastBlockedRaw);assert.equal(eastBlockedRaw.isError,true);assert.equal(eastBlocked.executed,false);assert.equal(eastBlocked.customer.status,'ACTIVE');assert.equal(eastBlocked.authzen.context.gate.authority,'INVALID');print('8. HEALTHY REGION DENIES FROM ACTUAL REVOKED GRAPH',{isError:eastBlockedRaw.isError,...eastBlocked});
    const westBlockedRaw=await westMcp.client.callTool({name:'delete_customer_data',arguments:{customerId:'4567'}});const westBlocked=parseTool(westBlockedRaw);assert.equal(westBlockedRaw.isError,true);assert.equal(westBlocked.executed,false);assert.equal(westBlocked.customer.status,'ACTIVE');assert.equal(westBlocked.authzen.context.gate.authority,'UNKNOWN');assert.equal(westBlocked.authzen.context.gate.reason,'replica_freshness_requirement_not_met');print('9. ISOLATED REGION FAILS CLOSED INSTEAD OF USING STALE AUTHORITY',{isError:westBlockedRaw.isError,...westBlocked});
    const sameToken=await verifyRemoteAccessToken({token,audience,allowedIssuer:issuer.url});assert.equal(sameToken.valid,true);print('10. SAME OAUTH TOKEN REMAINS LOCALLY VALID',{valid:sameToken.valid,jti:sameToken.payload?.jti,principal:sameToken.principal,actor:sameToken.actor});
    await postJson(`${west.url}/demo/network/heal`,{});const healed=await waitRevision(west.url,6);const healedRaw=await westMcp.client.callTool({name:'delete_customer_data',arguments:{customerId:'5678'}});const healedBlocked=parseTool(healedRaw);assert.equal(healedRaw.isError,true);assert.equal(healedBlocked.executed,false);assert.equal(healedBlocked.authzen.context.gate.authority,'INVALID');print('11. WEST HEALS, CATCHES UP, AND DENIES FROM THE REAL REVOKED STATE',{replica:healed,isError:healedRaw.isError,...healedBlocked});
    const mEast=await requestJson(`${east.url}/v1/metrics`);const mWest=await requestJson(`${west.url}/v1/metrics`);print('12. METERABLE VERIFICATION COUNTERS',{east:mEast,west:mWest,totalChecks:mEast.checks+mWest.checks});
    return{passed:true,bench};
  }finally{if(eastMcp)await eastMcp.client.close().catch(()=>{});if(westMcp)await westMcp.client.close().catch(()=>{});await stop(pdpWest);await stop(pdpEast);await stop(west);await stop(east);await stop(issuer);await stop(txB);await stop(txA);await stop(principal);await stop(control);await stop(trust)}
}
if(demoMode){try{const r=await runScenario();console.log('\n=== RESULT ===\nGATE v0.8 DISTRIBUTED CONSISTENCY DEMO PASSED');console.log(JSON.stringify({latency:r.bench,important:'bounded mode has a finite staleness window; strict mode trades availability/latency for current-state confirmation'},null,2))}catch(e){console.error(e);process.exitCode=1}}
else test('regional replicas use signed freshness leases, bounded staleness, fail-closed partitions and live cross-domain revocation',async()=>{const r=await runScenario();assert.equal(r.passed,true)});
